# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8afdd46ea949e520a4e2746cf9dff313e11c68400c79e37613e41b095655627417597bd2e379e00b1c1b0f79a2913b98c25611c7e8bc688b6c8bb16c4f6c583c

test:
  secret_key_base: 2ebccf404c6cc6aff51d77ad0b27ee2e673a4ffbdb9575afae8ded4c0ffeeb0c74d93d645d0f3405df7f509cc4befa66b9f97508a756b97b665f8e1a1a912209

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
